### ISSUE TITLE
签名算法获取不到最近交易价格

### ISSUE THREAD

**Issue by hongweipeng** [XuCcc/DuTracker#1]
浏览器访问：

![20190710143622](https://user-images.githubusercontent.com/7546325/60946191-282f9a00-a320-11e9-8aa8-35d8b9512a89.png)

爬虫取得的：

![20190710143748](https://user-images.githubusercontent.com/7546325/60946254-54e3b180-a320-11e9-81b7-43c13b51af64.png)

**Comment by hongweipeng** [comment]
已解决

**Comment by FengGuanxi** [comment]
朋友你好，我最近也在看这个，能不能请教一下你是怎么解决的呢

**Comment by hongweipeng** [comment]
换一下网址，签名本身没问题

**Comment by FengGuanxi** [comment]
我又尝试了一下，那么请问…具体的网址是什么样的呢…

**Comment by hongweipeng** [comment]
@FengGuanxi  加我q私聊：961365124 。这里不合适讨论

**Comment by never615** [comment]
android 7.0以上app的https请求无法抓包了是吧?

**Comment by never615** [comment]
接口升级了,签名也变了吧? 现在签名通不过了
@XuCcc
